### ISSUE TITLE
Current logic won't match different apostrophes in card names.

### ISSUE THREAD

**Issue by JERisBRISK** [alexwjacks/parallel-card-bot#2]
Examples:

!site "Antius' Forecast"
Sorry, I don't know the card Antius' Forecast

!site "Antius’ Forecast"
[https://parallel.life/cards/antius’-forecast](https://parallel.life/cards/antius%E2%80%99-forecast)

!site "archivist's pride"
Sorry, I don't know the card archivist's pride

!site "Archivist’s Pride"
[https://parallel.life/cards/archivist’s-pride](https://parallel.life/cards/archivist%E2%80%99s-pride)

This is due to the single quote character used in the JSON.

Discord uses ' but the JSON uses ’

**Comment by alexwjacks** [comment]
I eventually want to implement fuzzy matching, which would probably solve this without having to do any specific apostrophe matching.

**Comment by JERisBRISK** [comment]
Agreed. Something based on Levenshtein Distance is probably best, or at least easiest.
